### ISSUE TITLE
Update non-essential Dockerfile elements for new repository structure 

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-sweepers#2]
Currently, requests is installed manually, package is manually installed, and repo is cloned from Github

## 💡 Description

- [x] ~deps are installed from requirements.txt~ included as project install deps
- [x] registry-sweepers package is pulled from the local repository instance, not Github  (unless there's a reason not to - @jimmie @tloubrieu-jpl?  my thought is that development/testing is easier this way)
- [x] ~registry-sweepers package is installed into the venv and the venv is used when executing the driver~

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl we pull the package from an artifactory in docker images to make them as thin as possible, it comes from a recommendation that @nutjob4life made I think. We can discuss that. In that case we would push the package on pypi with the cicd and pull it from there in the docker image.

**Comment by alexdunnjpl** [comment]
Ah, gotcha - I may need to revert/alter that change then.  Will wait for feedback from Sean

**Comment by nutjob4life** [comment]
Hi @tloubrieu-jpl @alexdunnjpl. I think my recommendation was made for Java-based projects which would do things like:

1. `FROM java`
2. `COPY . /usr/app/src`
3. …install Apache Maven… (which is huge)
4. …run `mvn install`… (which downloads 429 Maven plugins, which is huge)
5. `ENTRYPOINT whatever`
6. …and not even remove Apache Maven or the `.m2` repository at the end

which results in gigabyte-sized images most of whose bytes are never actually executed at container time.

Python's a lot lighter weight and so doing `pip install .` instead of `pip install package-1.2.3 (from artifactory)` is a lot less of a concern.

(Besides: I often will do `docker container exec` and _actually edit_ source code in the image in order to debug things! 🤫)
